services:
  # Node.js Development
  api-dev:
    build:
      context: .
      target: development
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    depends_on:
      - redis
    networks:
      - app-network

  # Node.js Production
  api-prod:
    build:
      context: .
      target: production
    ports:
      - "3001:3000"
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    depends_on:
      - redis
    networks:
      - app-network
    
  # Supporting services
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - app-network

  # Database for real-world scenarios
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: sampledb
      POSTGRES_USER: Frank
      POSTGRES_PASSWORD: mom
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - app-network

volumes:
  redis-data:
  postgres-data:

networks:
  app-network:
    driver: bridge