version: '3.8'

services:
  # FastAPI Application (Production)
  api:
    build:
      context: ./api
      target: production
    environment:
      - SECRET_KEY=${SECRET_KEY}
      - REDIS_URL=${REDIS_URL}
    depends_on:
      - redis
    networks:
      - app-network
    restart: unless-stopped
    deploy:
      replicas: 3
      resources:
        limits:
          cpus: '0.5'
          memory: 256M
        reservations:
          cpus: '0.25'
          memory: 128M

  # Nginx Reverse Proxy (Production)
  nginx:
    build: ./nginx
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - api
    networks:
      - app-network
    restart: unless-stopped
    volumes:
      - ./ssl:/etc/ssl:ro
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: 64M

  # Redis Cache (Production)
  redis:
    image: redis:8.0.1-bookworm
    volumes:
      - redis_data:/data
    networks:
      - app-network
    restart: unless-stopped
    command: redis-server --appendonly yes --maxmemory 100mb --maxmemory-policy allkeys-lru

volumes:
  redis_data:
    driver: local

networks:
  app-network:
    driver: bridge